
const state={resumo:null,dados:null,selecionados:new Map(),removidos:new Set()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const sim=v=>['sim','s','1','true','ok','yes'].includes(norm(v));
function pill(v){return sim(v)?'<span class="pill ok">SIM</span>':(norm(v)?'<span class="pill warn">'+esc(v)+'</span>':'<span class="pill">—</span>');}
function toast(msg,erro=false){if(window.mostrarToast){window.mostrarToast(msg,erro?'erro':'ok');return;}alert(msg)}
async function carregarResumo(){
  document.getElementById('fila-body').innerHTML='<tr><td colspan="10" class="loading">Atualizando dados...</td></tr>';
  try{const r=await fetch('/api/expedicao/resumo');const d=await r.json();if(!r.ok)throw new Error(d.erro||'Erro ao carregar a expedição.');state.resumo=d;renderResumo();renderFila();}
  catch(e){document.getElementById('fila-body').innerHTML='<tr><td colspan="10" class="empty">'+esc(e.message)+'</td></tr>';}
}
function renderResumo(){const r=state.resumo?.resumo||{};document.getElementById('sum-pendentes').textContent=r.lojas_pendentes??0;document.getElementById('sum-capacidade').textContent=r.capacidade_lojas??0;document.getElementById('sum-prontas').textContent=r.lojas_saldo_individual??0;document.getElementById('sum-completas').textContent=r.kits_completos_pendentes??0;document.getElementById('sum-expansao').textContent=r.unidades_expansao??0;const pend=r.lojas_pendentes??0,cap=r.capacidade_lojas??0,kit=r.kits_completos_pendentes??0;const ready=r.lojas_saldo_individual??0;document.getElementById('hero-log-pend').textContent=pend;document.getElementById('hero-log-cap').textContent=cap;document.getElementById('hero-log-kit').textContent=kit;document.getElementById('hero-badge-ready').textContent=`${ready} prontas`;document.getElementById('hero-badge-risk').textContent=`${Math.max(0,pend-cap)} com risco`;document.getElementById('hero-badge-cap').textContent=`${cap} lojas possíveis`;}
function renderFila(){const body=document.getElementById('fila-body');const q=norm(document.getElementById('busca-loja').value);let lojas=(state.resumo?.lojas||[]).filter(x=>!q||norm([x.codigo,x.nome,x.cidade,x.uf,x.projeto].join(' ')).includes(q));if(!lojas.length){body.innerHTML='<tr><td colspan="10" class="empty">Nenhuma loja encontrada.</td></tr>';return;}const recomendada=(lojas.find(x=>Number(x.faltam||0)>0&&x.saldo_cobre_faltantes)||lojas.find(x=>Number(x.faltam||0)>0)||{}).codigo;body.innerHTML=lojas.map(x=>{const saldo=x.kit_completo?'Completo':x.saldo_cobre_faltantes?'Coberto':'Insuficiente';const saldoClass=x.kit_completo||x.saldo_cobre_faltantes?'ok':'danger';const rowClass=String(x.codigo)===String(recomendada)?'row-open fila-recomendada':'row-open';const dica=String(x.codigo)===String(recomendada)?(x.saldo_cobre_faltantes?'<div class="smart-tip">Próxima melhor opção</div>':'<div class="smart-tip warn">Próxima prioridade</div>'):'';return `<tr class="${rowClass}" ondblclick="abrirOperacao('${esc(x.codigo)}')"><td><span class="code">${esc(x.codigo)}</span><br><span style="color:var(--muted);font-size:10px">${esc(x.nome||'')} ${x.cidade?'· '+esc(x.cidade)+'/'+esc(x.uf):''}</span></td><td>${esc(x.projeto||'—')}</td><td>${esc(x.inauguracao||'A DEFINIR')}</td><td><div class="progress"><span style="width:${Math.max(0,Math.min(100,Number(x.percentual||0)))}%"></span></div><div class="progress-meta"><span>${Number(x.percentual||0).toFixed(1)}%</span><span>${x.ja_enviado}/${x.total_kit}</span></div></td><td class="num" style="color:${x.faltam?'var(--warn)':'var(--ok)'}">${x.faltam}</td><td><span class="pill ${saldoClass}">${saldo}</span></td><td>${pill(x.em_separacao)}</td><td>${pill(x.equip_separado)}</td><td>${pill(x.enviada)}</td><td>${dica}<button type="button" class="ui-btn ui-btn-primary" style="padding:6px 9px;font-size:10px;margin-top:6px" onclick="abrirOperacao('${esc(x.codigo)}')">Abrir expedição</button></td></tr>`}).join('');}
function selPorKit(k){let n=0;for(const x of state.selecionados.values())if(String(x._kitCodigo||'')===String(k.codigo||'')&&String(x._kitDescricao||'')===String(k.descricao||''))n++;return n;}
function adicionar(item,k,forcar=false){const id=Number(item?.id);if(!id||!k||state.selecionados.has(id))return false;if(!forcar&&state.removidos.has(id))return false;if(selPorKit(k)>=Number(k.faltam||0))return false;state.selecionados.set(id,{...item,_kitCodigo:k.codigo||'',_kitDescricao:k.descricao||''});state.removidos.delete(id);return true;}
function renderKit(){const b=document.getElementById('kit-body'),linhas=state.dados?.kit||[];if(!linhas.length){b.innerHTML='<tr><td colspan="7" class="empty">Kit sem itens.</td></tr>';return;}b.innerHTML=linhas.map((k,i)=>{const s=selPorKit(k),f=Math.max(0,Number(k.faltam||0)-s),d=Math.max(0,Number(k.disponivel_expansao||0)-s);return `<tr><td class="code">${esc(k.codigo||'-')}</td><td>${esc(k.descricao||'-')}</td><td class="num">${k.necessario}</td><td class="num" style="color:var(--ok)">${k.ja_enviado}</td><td class="num" style="color:${f?'var(--warn)':'var(--ok)'}">${f}</td><td class="num">${d}</td><td>${f?`<button type="button" class="ui-btn ui-btn-secondary" style="padding:5px 8px;font-size:10px" onclick="selecionarLinha(${i})">Selecionar ${Math.min(f,d)}</button>`:'<span class="pill ok">OK</span>'}</td></tr>`}).join('');}
window.selecionarLinha=i=>{const k=(state.dados?.kit||[])[Number(i)];if(!k)return;let n=Math.max(0,Number(k.faltam||0)-selPorKit(k));for(const it of (k.unidades||[])){if(n<=0)break;if(adicionar(it,k,true))n--;}renderSelecionados();renderKit();};
window.removerSel=id=>{const n=Number(id);state.selecionados.delete(n);state.removidos.add(n);renderSelecionados();renderKit();validar();toast('Equipamento removido desta expedição. Os demais itens continuam disponíveis para confirmação.');};
window.atualizarSel=(id,campo,val)=>{const x=state.selecionados.get(Number(id));if(x){x[campo]=val;validar();}};
function renderSelecionados(){const b=document.getElementById('selecionados-body'),arr=[...state.selecionados.values()];document.getElementById('sel-resumo').textContent=`${arr.length} selecionado(s)`;if(!arr.length)b.innerHTML='<tr><td colspan="6" class="empty">Nenhum equipamento selecionado.</td></tr>';else b.innerHTML=arr.map(x=>`<tr><td><strong>${esc(x.codigo||'-')}</strong><br><span style="color:var(--muted)">${esc(x.descricao||'-')}</span></td><td class="num">#${x.id}</td><td><input class="${x.nro_imobilizado?'':'missing'}" value="${esc(x.nro_imobilizado||'')}" oninput="atualizarSel(${x.id},'nro_imobilizado',this.value);this.classList.toggle('missing',!this.value.trim())"></td><td><input class="${x.nro_serie?'':'missing'}" value="${esc(x.nro_serie||'')}" oninput="atualizarSel(${x.id},'nro_serie',this.value);this.classList.toggle('missing',!this.value.trim())"></td><td><input class="${x.nro_patrimonio?'':'missing'}" value="${esc(x.nro_patrimonio||'')}" oninput="atualizarSel(${x.id},'nro_patrimonio',this.value);this.classList.toggle('missing',!this.value.trim())"></td><td><div class="selected-actions"><button type="button" class="ui-btn edit-btn" style="padding:5px 7px;font-size:10px" onclick="editarSel(${x.id})">Editar</button><button type="button" class="ui-btn ui-btn-danger" style="padding:5px 7px;font-size:10px" onclick="removerSel(${x.id})">Remover</button></div></td></tr>`).join('');validar();}
function atualizarAssistente(){const arr=[...state.selecionados.values()];const pend=arr.filter(x=>!String(x.nro_imobilizado||'').trim()||!String(x.nro_serie||'').trim()||!String(x.nro_patrimonio||'').trim());const fiscal=Boolean(document.getElementById('op-nf')?.value.trim()&&document.getElementById('op-data')?.value);document.getElementById('assist-selecionados').textContent=arr.length;document.getElementById('assist-pendencias').textContent=pend.length;document.getElementById('assist-fiscal').textContent=fiscal?'OK':'Não';const statusEl=document.getElementById('assist-status');const banner=document.getElementById('assist-banner');if(!document.getElementById('op-filial').value){statusEl.textContent='Aguardando';banner.className='assist-banner';banner.textContent='Abra uma filial para que a baixa assistida monte automaticamente a operação.';return;}if(!arr.length){statusEl.textContent='Selecionar';banner.className='assist-banner';banner.textContent='Use a seleção automática ou escolha os itens do Kit para começar a montar a expedição.';return;}if(pend.length){statusEl.textContent='Revisar';banner.className='assist-banner warn';banner.textContent=`Revise ${pend.length} pendência(s) de imobilizado, série ou patrimônio antes da confirmação.`;return;}if(!fiscal){statusEl.textContent='Fiscal';banner.className='assist-banner';banner.textContent='Equipamentos prontos. Agora informe a NF de saída e a data para liberar a confirmação.';return;}statusEl.textContent='Pronto';banner.className='assist-banner ok';banner.textContent=`Operação pronta: ${arr.length} equipamento(s) podem ser baixados agora em uma única confirmação.`;}
function atualizarChecklist(){const filial=document.getElementById('op-filial').value;const arr=[...state.selecionados.values()];const pend=arr.filter(x=>!String(x.nro_imobilizado||'').trim()||!String(x.nro_serie||'').trim()||!String(x.nro_patrimonio||'').trim());const fiscal=Boolean(document.getElementById('op-nf')?.value.trim()&&document.getElementById('op-data')?.value);const marcar=(id,ok,texto)=>{const el=document.getElementById(id);if(!el)return;el.classList.toggle('ok',!!ok);el.classList.toggle('warn',!ok);const t=el.querySelector('span[id]');if(t&&texto)t.textContent=texto;};marcar('check-filial',!!filial,filial?`Filial ${filial} pronta para expedição.`:'Selecione uma loja na fila para iniciar.');marcar('check-equip',arr.length>0,arr.length?`${arr.length} equipamento(s) preparados para a operação.`:'A seleção automática prepara os itens disponíveis do Kit.');marcar('check-cadastro',arr.length>0&&pend.length===0,arr.length?pend.length?`${pend.length} pendência(s) ainda precisam ser corrigidas.`:'Todos os campos obrigatórios dos equipamentos foram preenchidos.':'Imobilizado, série e patrimônio precisam estar completos.');marcar('check-fiscal',fiscal,fiscal?'NF e data informadas.':'Informe a nota fiscal e a data da saída para liberar a confirmação.');document.getElementById('confirm-total-equip').textContent=`${arr.length} item(ns)`;document.getElementById('confirm-destino').textContent=filial||'—';let etapa='Aguardando seleção';let nota='Quando todos os passos estiverem verdes, a baixa poderá ser confirmada com segurança.';if(filial&&!arr.length){etapa='Selecionar itens';nota='Abra a loja e use a seleção automática ou escolha manualmente os equipamentos do Kit.';}else if(arr.length&&pend.length){etapa='Revisar cadastro';nota=`Existem ${pend.length} pendência(s) em imobilizado, série ou patrimônio.`;}else if(arr.length&&!fiscal){etapa='Informar NF / data';nota='Equipamentos prontos. Falta apenas preencher NF e data para concluir.';}else if(arr.length&&fiscal&&pend.length===0){etapa='Pronto para confirmar';nota='Todos os critérios da operação foram atendidos. Você já pode confirmar a baixa.';}document.getElementById('confirm-etapa').textContent=etapa;document.getElementById('confirm-note').textContent=nota;}
function atualizarFluxo(){
 const arr=[...state.selecionados.values()];
 const pend=arr.filter(x=>!String(x.nro_imobilizado||'').trim()||!String(x.nro_serie||'').trim()||!String(x.nro_patrimonio||'').trim());
 const fiscal=Boolean(document.getElementById('op-nf')?.value.trim()&&document.getElementById('op-data')?.value);
 document.querySelectorAll('#flow-steps .flow-step').forEach(x=>x.classList.remove('active','done'));
 const steps=[...document.querySelectorAll('#flow-steps .flow-step')];
 if(!steps.length)return;
 steps[0].classList.add('done');
 if(arr.length&&pend.length===0){steps[1].classList.add('done');}else{steps[1].classList.add('active');return;}
 if(fiscal){steps[2].classList.add('done');steps[3].classList.add('active');}else{steps[2].classList.add('active');}
}
function validar(){const arr=[...state.selecionados.values()],pend=arr.filter(x=>!String(x.nro_imobilizado||'').trim()||!String(x.nro_serie||'').trim()||!String(x.nro_patrimonio||'').trim()),cab=Boolean(document.getElementById('op-filial').value&&document.getElementById('op-nf').value.trim()&&document.getElementById('op-data').value),btn=document.getElementById('confirmar'),box=document.getElementById('validacao');const ok=arr.length&&pend.length===0&&cab;btn.disabled=!ok;if(!arr.length){box.className='alert';box.textContent='Selecione os equipamentos do Kit para continuar.';}else if(pend.length){box.className='alert';box.textContent=`Atenção: ${pend.length} equipamento(s) ainda estão sem imobilizado, série ou patrimônio.`;}else if(!cab){box.className='alert';box.textContent='Equipamentos prontos. Informe NF de saída e data para confirmar.';}else{box.className='alert ok';box.textContent=`Pronto para baixar ${arr.length} equipamento(s) em uma única operação com auditoria.`;}atualizarFluxo();atualizarAssistente();atualizarChecklist();}
window.abrirOperacao=async codigo=>{try{const r=await fetch(`/api/baixa-rapida/filial/${encodeURIComponent(codigo)}`);const d=await r.json();if(!r.ok)throw new Error(d.erro||'Erro ao abrir expedição.');state.dados=d;state.selecionados.clear();state.removidos.clear();const f=d.filial||{},a=d.acompanhamento||{},res=d.resumo||{};document.getElementById('operacao-panel').hidden=false;document.getElementById('op-titulo').textContent=`Expedição · Filial ${f.codigo||codigo}`;document.getElementById('op-subtitulo').textContent=[f.nome,f.cidade,f.uf].filter(Boolean).join(' · ');document.getElementById('op-filial').value=f.codigo||codigo;document.getElementById('op-nf').value='';document.getElementById('op-data').value=new Date().toISOString().slice(0,10);document.getElementById('op-vd').value='';document.getElementById('ctx-projeto').textContent=a.projeto||'—';document.getElementById('ctx-obra').textContent=a.term_obra||'A DEFINIR';document.getElementById('ctx-ti').textContent=a.entrada_ti||'A DEFINIR';document.getElementById('ctx-inaug').textContent=a.inauguracao||f.previsao_abertura||'A DEFINIR';document.getElementById('op-kit').textContent=res.total_kit||0;document.getElementById('op-enviado').textContent=res.ja_enviado||0;document.getElementById('op-falta').textContent=res.faltam||0;document.getElementById('op-percentual').textContent=`${Number(res.percentual||0).toFixed(1)}%`;document.getElementById('op-progress').style.width=`${Math.max(0,Math.min(100,Number(res.percentual||0)))}%`;auto(true);atualizarAssistente();atualizarChecklist();document.getElementById('operacao-panel').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.getElementById('op-nf')?.focus(),450);}catch(e){toast(e.message,true);}};
function auto(silencioso=false){state.selecionados.clear();if(!silencioso)state.removidos.clear();for(const k of (state.dados?.kit||[])){let n=Number(k.faltam||0);for(const it of (k.unidades||[])){if(n<=0)break;if(adicionar(it,k))n--;}}renderSelecionados();renderKit();if(!state.selecionados.size&&!silencioso)toast('Nenhuma unidade disponível para completar o Kit desta filial.',true);if(state.selecionados.size&&!silencioso)toast(`${state.selecionados.size} equipamento(s) selecionado(s) automaticamente.`);atualizarAssistente();atualizarChecklist();}
window.editarSel=id=>{const x=state.selecionados.get(Number(id));if(!x)return;document.getElementById('edit-item-id').value=x.id;document.getElementById('edit-item-meta').textContent=`${x.codigo||'-'} · ${x.descricao||'-'} · ID #${x.id}`;document.getElementById('edit-imobilizado').value=x.nro_imobilizado||'';document.getElementById('edit-serie').value=x.nro_serie||'';document.getElementById('edit-patrimonio').value=x.nro_patrimonio||'';document.getElementById('edit-item-dialog').showModal();};
function salvarEdicaoSel(){const id=Number(document.getElementById('edit-item-id').value),x=state.selecionados.get(id);if(!x)return;x.nro_imobilizado=document.getElementById('edit-imobilizado').value.trim();x.nro_serie=document.getElementById('edit-serie').value.trim();x.nro_patrimonio=document.getElementById('edit-patrimonio').value.trim();document.getElementById('edit-item-dialog').close();renderSelecionados();toast('Equipamento atualizado na seleção.');}
function baixarModeloPreenchimento(){const ids=[...state.selecionados.keys()];if(!ids.length){toast('Selecione ao menos um equipamento antes de baixar o modelo.',true);return;}window.location.href='/api/baixa-rapida/modelo-preenchimento?ids='+encodeURIComponent(ids.join(','));}
async function importarPreenchimento(file){const status=document.getElementById('upload-status');status.className='upload-status';status.textContent='Processando arquivo...';const fd=new FormData();fd.append('arquivo',file);try{const r=await fetch('/api/baixa-rapida/importar-preenchimento',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Não foi possível processar o Excel.');let aplicadas=0,ignoradas=0;for(const linha of (d.linhas||[])){const id=Number(linha.id_estoque);const x=state.selecionados.get(id);if(!x){ignoradas++;continue;}if(linha.nro_imobilizado!==undefined)x.nro_imobilizado=String(linha.nro_imobilizado||'').trim();if(linha.nro_serie!==undefined)x.nro_serie=String(linha.nro_serie||'').trim();if(linha.nro_patrimonio!==undefined)x.nro_patrimonio=String(linha.nro_patrimonio||'').trim();aplicadas++;}renderSelecionados();status.className='upload-status ok';status.textContent=`${aplicadas} item(ns) preenchido(s)`+(ignoradas?` · ${ignoradas} ignorado(s) fora da seleção`:``);toast(`${aplicadas} equipamento(s) preenchido(s) pelo Excel.`);}catch(e){status.className='upload-status erro';status.textContent=e.message;toast(e.message,true);}finally{document.getElementById('arquivo-preenchimento').value='';}}
function scanAdd(){const termo=norm(document.getElementById('scan-input').value);if(!termo)return;for(const k of (state.dados?.kit||[])){if(selPorKit(k)>=Number(k.faltam||0))continue;const it=(k.unidades||[]).find(x=>[x.nro_patrimonio,x.nro_serie,x.nro_imobilizado].some(v=>norm(v)===termo));if(it){const ok=adicionar(it,k);document.getElementById('scan-input').value='';renderSelecionados();renderKit();toast(ok?'Equipamento adicionado.':'Equipamento já selecionado.',!ok);return;}}toast('Equipamento não encontrado entre os itens que faltam para este Kit.',true);}
async function confirmar(){validar();const btn=document.getElementById('confirmar');if(btn.disabled)return;const itens=[...state.selecionados.values()].map(x=>({id:x.id,nro_imobilizado:x.nro_imobilizado,nro_serie:x.nro_serie,nro_patrimonio:x.nro_patrimonio})),filial=document.getElementById('op-filial').value;if(!confirm(`Confirmar a baixa de ${itens.length} equipamento(s) para a filial ${filial}?`))return;const old=btn.textContent;btn.disabled=true;btn.textContent='Confirmando...';try{const r=await fetch('/api/baixa-rapida/confirmar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filial_destino:filial,removidos:[...state.removidos],nf_saida:document.getElementById('op-nf').value.trim(),data_saida:document.getElementById('op-data').value,vd_loja:document.getElementById('op-vd').value.trim(),itens})});const d=await r.json();if(!r.ok)throw new Error(d.erro||'Erro ao concluir a baixa.');toast(d.ativacao_filial?.ativada?`Baixa concluída: ${d.atualizados} equipamento(s). Filial ativada/inaugurada.`:`Baixa concluída: ${d.atualizados} equipamento(s). Ainda faltam ${d.resumo?.faltam||0} unidade(s).`);await carregarResumo();if(!d.ativacao_filial?.ativada)await abrirOperacao(filial);else document.getElementById('operacao-panel').hidden=true;}catch(e){toast(e.message,true);}finally{btn.textContent=old;validar();}}
function abrirProximaPronta(){const lojas=state.resumo?.lojas||[];const alvo=lojas.find(x=>Number(x.faltam||0)>0&&x.saldo_cobre_faltantes)||lojas.find(x=>Number(x.faltam||0)>0);if(!alvo){toast('Nenhuma loja pendente disponível para expedição.',true);return;}abrirOperacao(alvo.codigo);}
document.getElementById('proxima-pronta').addEventListener('click',abrirProximaPronta);document.getElementById('atualizar-resumo').addEventListener('click',carregarResumo);document.getElementById('busca-loja').addEventListener('input',renderFila);document.getElementById('auto').addEventListener('click',auto);document.getElementById('limpar').addEventListener('click',()=>{state.selecionados.clear();state.removidos.clear();renderSelecionados();renderKit();});document.getElementById('scan-add').addEventListener('click',scanAdd);document.getElementById('scan-input').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();scanAdd();}});document.getElementById('baixar-modelo').addEventListener('click',baixarModeloPreenchimento);document.getElementById('importar-preenchimento').addEventListener('click',()=>document.getElementById('arquivo-preenchimento').click());document.getElementById('arquivo-preenchimento').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importarPreenchimento(f);});document.getElementById('edit-item-fechar').addEventListener('click',()=>document.getElementById('edit-item-dialog').close());document.getElementById('edit-item-cancelar').addEventListener('click',()=>document.getElementById('edit-item-dialog').close());document.getElementById('edit-item-salvar').addEventListener('click',salvarEdicaoSel);document.getElementById('confirmar').addEventListener('click',confirmar);document.getElementById('fechar-operacao').addEventListener('click',()=>{document.getElementById('operacao-panel').hidden=true;atualizarAssistente();atualizarChecklist();});['op-nf','op-data'].forEach(id=>document.getElementById(id).addEventListener('input',validar));carregarResumo();atualizarAssistente();atualizarChecklist();
